addons:
  apt:
    packages:
      - cmake
      - device-tree-compiler
install:
  - wget https://github.com/chino-os/chino-gnu-toolchain/releases/download/preview3/chino-gnu-toolchain-preview3.tar.gz
  - sudo tar -xzf chino-gnu-toolchain-preview3.tar.gz -C /opt
  - export PATH=$PATH:/opt/chino/bin
script:
 - chmod +x build.sh
 - mkdir build && cd build
 - ../build.sh cortex-m3 stm32f103rc
 - make firmware
