addons:
  apt:
    packages:
      - cmake
      - device-tree-compiler
      - xorriso
install:
  - wget https://github.com/chino-os/chino-gnu-toolchain/releases/download/preview3/chino-gnu-toolchain-preview3.tar.gz
  - sudo tar -xzf chino-gnu-toolchain-preview3.tar.gz -C /opt
  - export PATH=$PATH:/opt/chino/bin
  - >
    if [ "$BOARD" == "pc" ]; then
      git clone git://git.code.sf.net/p/gnu-efi/code gnu-efi-code
      cd gnu-efi-code
      make && sudo make install
      cd ..
    fi
matrix:
  include:
  - name: "cortex-m3 stm32f103rc"
    env: ARCH=cortex-m3 BOARD=stm32f103rc
  - name: "x86_64 pc"
    env: ARCH=x86_64 BOARD=pc
script:
 - chmod +x build.sh
 - mkdir build && cd build
 - ../build.sh $ARCH $BOARD
 - make firmware
