version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    git submodule update --init --recursive

    mkdir build && cd build

    cmake .. -G "Visual Studio 15 2017 Win64" -DARCH="win-x86_64"  -DBOARD="win32-simulator"

    msbuild ALL_BUILD.vcxproj