if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "(x86)|(X86)")
    if (MSVC)
        add_compile_options(/arch:SSE2 -maes)
    else()
        add_compile_options(-msse2 -maes)
    endif()
elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES "(amd64)|(AMD64)|(x86_64)|(X86_64)")
    if (MSVC)
        add_compile_options(/arch:AVX -maes)
    else()
        add_compile_options(-mavx -maes)
    endif()
endif()
