get_filename_component(CHINO_TOOLCHAIN_DIR ${CMAKE_C_COMPILER} DIRECTORY)
get_filename_component(CHINO_TOOLCHAIN_PREFIX ${CMAKE_C_COMPILER} NAME_WE)
string(REPLACE "gcc" "" CHINO_TOOLCHAIN_PREFIX ${CHINO_TOOLCHAIN_PREFIX})
set(CMAKE_OBJCOPY ${CHINO_TOOLCHAIN_DIR}/${CHINO_TOOLCHAIN_PREFIX}objcopy)